use gdnative::prelude::*;
// pub mod animation;
pub mod bitmap;
pub mod camera;
// pub mod camerazone;
pub mod collisionvol;
pub mod gameobj;
pub mod hfog;
pub mod light;
pub mod lod;
pub mod material;
pub mod materialanim;
pub mod materialobj;
pub mod mesh;
pub mod node;
// pub mod occluder;
pub mod omni;
// pub mod particles;
pub mod rotshape;
// pub mod rtc;
pub mod skin;
pub mod sound;
pub mod spline;
pub mod surface;
pub mod warp;
// pub mod world;

pub use bitmap::*;
pub use camera::*;
pub use collisionvol::*;
pub use gameobj::*;
pub use hfog::*;
pub use light::*;
pub use lod::*;
pub use material::*;
pub use materialanim::*;
pub use materialobj::*;
pub use mesh::*;
pub use node::*;
pub use omni::*;
pub use rotshape::*;
pub use skin::*;
pub use sound::*;
pub use spline::*;
pub use surface::*;
pub use warp::*;

pub fn init(handle: InitHandle) {
    handle.add_class::<BitmapView>();
    handle.add_class::<CameraView>();
    handle.add_class::<CollisionVolView>();
    handle.add_class::<GameObjView>();
    handle.add_class::<HFogView>();
    handle.add_class::<LightView>();
    handle.add_class::<LodView>();
    handle.add_class::<MaterialView>();
    handle.add_class::<MaterialAnimView>();
    handle.add_class::<MaterialObjView>();
    handle.add_class::<MeshView>();
    handle.add_class::<NodeView>();
    handle.add_class::<OmniView>();
    handle.add_class::<RotShapeView>();
    handle.add_class::<SkinView>();
    handle.add_class::<SoundView>();
    handle.add_class::<SplineView>();
    handle.add_class::<SurfaceView>();
    handle.add_class::<WarpView>();
}
